---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authelia
  namespace: authelia
  labels:
    app: authelia
data:
  jwt_secret: YW5fdW5zZWN1cmVfc2VjcmV0  # an_unsecure_secret
  ldap_password: cGFzc3dvcmQ=  # password
  session: dW5zZWN1cmVfcGFzc3dvcmQ=  # unsecure_password
  sql_password: cGFzc3dvcmQ=  # password
  encryption_key: YV9ub3Rfc29fc2VjdXJlX2VuY3J5cHRpb25fa2V5
...
