---
version: "3"
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=authelia
    networks:
      - authelianet
...
