---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-service
  namespace: authelia
  labels:
    app: nginx-ingress-controller
spec:
  selector:
    app: nginx-ingress-controller
  type: NodePort
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
...
